### ISSUE TITLE
Can you add speed informations to edges?

### ISSUE THREAD

**Issue by hansglick** [Tristramg/osm4routing2#18]
Hi guys,

I was thinking, it would be awesome to add speed limit to the edges.csv output.

Bye!

**Comment by Tristramg** [comment]
Hello,

At first I though “easy!”, but the I looked into the details.

The tag `maxspeed` is only set on [15M ways](https://taginfo.openstreetmap.org/keys/maxspeed) out of [200M](https://taginfo.openstreetmap.org/keys/highway) roads.

There are [defaults values](https://wiki.openstreetmap.org/wiki/Key:maxspeed) but as they are country dependent, it gets quite complicated for such a trivial project as osm4routing :/

**Comment by hansglick** [comment]
Hi,

OK, indeed no need to add it.
Thks guys!

Bybye!!

**Comment by Tristramg** [comment]
I’m closing as for now it seems a bit too ambitious
