### ISSUE TITLE
osm4routing doesn't work on ubuntu

### ISSUE THREAD

**Issue by HelloJowet** [Tristramg/osm4routing2#20]
On my Mac, osm4routing works without any problems. 
However, when I execute it with the same osm input file on Ubuntu (22.04), I get the following error message:

```
thread 'main' panicked at 'assertion failed: len <= MAX_INLINE', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/smartstring-0.2.10/src/inline.rs:41:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/panicking.rs:114:5
   3: smartstring::inline::InlineString::as_str
   4: flat_map::flat_map::FlatMap<K,V>::insert
   5: <osmpbfreader::groups::DenseNodes as core::iter::traits::iterator::Iterator>::next
   6: <osmpbfreader::groups::OsmObjs as core::iter::traits::iterator::Iterator>::next
   7: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
   8: <osmpbfreader::blobs::OsmObjs as core::iter::traits::iterator::Iterator>::next
   9: <osmpbfreader::reader::Iter<R> as core::iter::traits::iterator::Iterator>::next
  10: <core::iter::adapters::flatten::Flatten<I> as core::iter::traits::iterator::Iterator>::next
  11: osm4routing::reader::read
  12: osm4routing::main
```

I tried to use the [official rust docker image](https://hub.docker.com/_/rust) too, but got the same error.

**Comment by Tristramg** [comment]
Hello,

That is a bit strange, I have always developed it under ubuntu (different releases, currently on 22.10).

Using https://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf and the command
`cargo run --release -- ile-de-france-latest.osm.pbf`
it worked for me. Could you try it?

Maybe there is a problem with your dataset that the code doesn’t handle as it should. If so, could you provide the pbf file you used?

Thank you in advance

**Comment by p4r4xor** [comment]
Same issue for me too. Doesn't work on mac, tried both cargo install and from source (used the pbf @Tristramg linked above).

**Comment by Tristramg** [comment]
Thank you for this feedback. This is quite annoying, I’ll be asking to use
other computers to see if I can reproduce the issue

It seems to happen is osmpbfreader. Maybe there is some strange problem
with unpined dependencies

**Comment by Tristramg** [comment]
I couldn’t reproduce it, but it seems there was an issue in a library https://github.com/TeXitoi/osmpbfreader-rs/pull/45

Could you re-test if it actually fixed your issue?

**Comment by HelloJowet** [comment]
Hello,

It works!! Thank you very much. :)
One small thing: could you please add a new version to the cargo package? That would be very helpful.
Thanks

**Comment by Tristramg** [comment]
Perfect, I’ve published the fixed version.

Just out of curiosity: in what context are you using this crate?

**Comment by HelloJowet** [comment]
I work for an infrastructure company. The question we are answering with our project is which addresses we can potentially connect to our infrastructure. Since we needed a graph for all of Germany, creating the graph on a country size level was a challenge. Packages like osm2pgrouting were extremely slow in our case. Your package has significantly improved the execution time of our workflow. Thank you for your great work.

**Comment by p4r4xor** [comment]
Works! Thanks a lot for your effort :)
