### ISSUE TITLE
Help for execution

### ISSUE THREAD

**Issue by SRohitNaik** [Tristramg/osm4routing2#9]
First, I want execute the code with the given example data. Then, I want to try with  "mumbai.osm.pbf" file downloaded from Openstreetmap. 
I want to know , how to execute and see the output? How to get the generate csv file?

**Comment by SRohitNaik** [comment]
![osm4rounting2 error](https://user-images.githubusercontent.com/47601404/54474142-2db02400-4807-11e9-8bcc-2cceedbf1302.PNG)

**Comment by antoine-de** [comment]
Hi,
Where did you download the file ?

I tried it with an osm file and it seems to work fine.
It generates a `node.csv`  and a `edge.csv` files

**Comment by SRohitNaik** [comment]
I have downloaded osm4rounting2-master on ubuntu and placed it on desktop. I tried to execute by giving command "cargo run src/main.rs" . I am getting same error. Please help in executing it.
